package br.com.t4acontrol.backend.navigation;

import br.com.t4acontrol.backend.location.LocationSnapshot;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Provider-neutral DEBUG diagnostics for instruction semantics and rider/route divergence.
 *
 * <p>This component never changes navigation state. It only describes what the routing provider
 * supplied and records evidence when the physical trace stops matching the route while a
 * directional instruction is active. A divergence event is deliberately evidence, not a claim
 * about rider intent: later analysis can distinguish deliberate choice, bad routing, bad
 * normalization, GPS error or UI/guidance error.
 */
public final class NavigationInstructionDiagnostics {
  public enum Kind {
    INSTRUCTION_FOCUS,
    INSTRUCTION_DIVERGENCE
  }

  public static final class Event {
    public final Kind kind;
    public final String summary;

    Event(Kind kind, String summary) {
      this.kind = kind;
      this.summary = summary;
    }
  }

  private String focusedInstructionKey = "";
  private String divergenceInstructionKey = "";

  public void reset() {
    focusedInstructionKey = "";
    divergenceInstructionKey = "";
  }

  /** Returns zero or more diagnostics generated by this navigation observation. */
  public List<Event> observe(
      NavigationState previous,
      NavigationState current,
      LocationSnapshot location,
      RouteProgressSnapshot progress) {
    if (current == null) return Collections.emptyList();

    List<Event> events = new ArrayList<>(2);
    NavigationInstruction instruction = current.instruction;
    String key = instructionKey(current);

    if (instruction != null && !key.equals(focusedInstructionKey)) {
      focusedInstructionKey = key;
      divergenceInstructionKey = "";
      events.add(new Event(Kind.INSTRUCTION_FOCUS, focusSummary(current)));
    }

    NavigationInstruction activeInstruction = instruction;
    NavigationState sourceState = current;
    if (current.status == NavigationState.Status.OFF_ROUTE
        && previous != null
        && previous.instruction != null) {
      activeInstruction = previous.instruction;
      sourceState = previous;
    }

    if (current.status == NavigationState.Status.OFF_ROUTE
        && activeInstruction != null
        && isDirectional(activeInstruction.maneuver)) {
      String divergenceKey = instructionKey(sourceState);
      if (!divergenceKey.equals(divergenceInstructionKey)) {
        divergenceInstructionKey = divergenceKey;
        events.add(new Event(
            Kind.INSTRUCTION_DIVERGENCE,
            divergenceSummary(sourceState, activeInstruction, location, progress)));
      }
    }

    return events;
  }

  private static String focusSummary(NavigationState state) {
    NavigationInstruction instruction = state.instruction;
    NavigationStepMetadata metadata = instruction.metadata;
    StringBuilder value = new StringBuilder();
    value.append("leg=").append(state.legIndex)
        .append(" instruction=").append(state.instructionIndex)
        .append(" id=").append(instruction.id)
        .append(" maneuver=").append(instruction.maneuver)
        .append(" distance=").append(state.distanceToInstructionMeters)
        .append(" text=").append(quote(instruction.text));

    if (metadata == null) {
      return value.append(" metadata=none").toString();
    }

    value.append(" context=").append(metadata.context)
        .append(" severity=").append(metadata.severity)
        .append(" rawType=").append(quote(metadata.rawType))
        .append(" rawModifier=").append(quote(metadata.rawModifier))
        .append(" bearingBefore=").append(metadata.bearingBefore)
        .append(" bearingAfter=").append(metadata.bearingAfter)
        .append(" roadName=").append(quote(metadata.roadName))
        .append(" roadRef=").append(quote(metadata.roadRef))
        .append(" destinations=").append(quote(metadata.destinations))
        .append(" exits=").append(quote(metadata.exits))
        .append(" mode=").append(quote(metadata.mode))
        .append(" drivingSide=").append(quote(metadata.drivingSide))
        .append(" intersections=").append(intersectionsSummary(metadata.intersections));
    return value.toString();
  }

  private static String divergenceSummary(
      NavigationState sourceState,
      NavigationInstruction instruction,
      LocationSnapshot location,
      RouteProgressSnapshot progress) {
    NavigationStepMetadata metadata = instruction.metadata;
    StringBuilder value = new StringBuilder();
    value.append("classification=possible_instruction_not_followed")
        .append(" leg=").append(sourceState.legIndex)
        .append(" instruction=").append(sourceState.instructionIndex)
        .append(" id=").append(instruction.id)
        .append(" maneuver=").append(instruction.maneuver)
        .append(" expectedDistance=").append(sourceState.distanceToInstructionMeters);

    if (metadata != null) {
      value.append(" context=").append(metadata.context)
          .append(" severity=").append(metadata.severity)
          .append(" rawType=").append(quote(metadata.rawType))
          .append(" rawModifier=").append(quote(metadata.rawModifier))
          .append(" bearingBefore=").append(metadata.bearingBefore)
          .append(" expectedBearingAfter=").append(metadata.bearingAfter)
          .append(" roadName=").append(quote(metadata.roadName));
    }

    if (location != null) {
      value.append(" lat=").append(location.latitude)
          .append(" lon=").append(location.longitude)
          .append(" accuracy=").append(location.accuracyMeters)
          .append(" speedKmh=").append(location.gpsSpeedKmh)
          .append(" actualBearing=").append(location.bearingDegrees);
      if (metadata != null
          && metadata.bearingAfter >= 0
          && location.bearingDegrees != null
          && Double.isFinite(location.bearingDegrees)) {
        value.append(" bearingDelta=")
            .append(RouteGeometry.angularDifferenceDegrees(
                location.bearingDegrees, metadata.bearingAfter));
      }
    }

    if (progress != null && progress.available()) {
      value.append(" routeOffset=").append(progress.routeOffsetMeters)
          .append(" lateralError=").append(progress.lateralErrorMeters)
          .append(" progressConsistent=").append(progress.progressConsistent);
    }

    value.append(" interpretation=evidence_only");
    return value.toString();
  }

  private static String intersectionsSummary(List<NavigationStepMetadata.Intersection> intersections) {
    if (intersections == null || intersections.isEmpty()) return "[]";
    StringBuilder value = new StringBuilder("[");
    for (int index = 0; index < intersections.size(); index++) {
      if (index > 0) value.append(';');
      NavigationStepMetadata.Intersection intersection = intersections.get(index);
      value.append("{")
          .append("lat=").append(intersection.latitude)
          .append(",lon=").append(intersection.longitude)
          .append(",bearings=").append(intersection.bearings)
          .append(",entry=").append(intersection.entry)
          .append(",in=").append(intersection.inIndex)
          .append(",out=").append(intersection.outIndex)
          .append(",classes=").append(intersection.classes)
          .append("}");
    }
    return value.append(']').toString();
  }

  private static boolean isDirectional(NavigationInstruction.Maneuver maneuver) {
    return maneuver == NavigationInstruction.Maneuver.TURN_LEFT
        || maneuver == NavigationInstruction.Maneuver.TURN_RIGHT
        || maneuver == NavigationInstruction.Maneuver.U_TURN
        || maneuver == NavigationInstruction.Maneuver.ROUNDABOUT;
  }

  private static String instructionKey(NavigationState state) {
    if (state == null || state.instruction == null) return "";
    return state.legIndex + "|" + state.instructionIndex + "|" + state.instruction.id;
  }

  private static String quote(String value) {
    if (value == null) return "null";
    return '"' + value.replace("\\", "\\\\").replace("\"", "\\\"") + '"';
  }
}
